name: MacAppStoreDiscovery
options:
  bundleIdPrefix: com.iosstore
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  MACOSX_DEPLOYMENT_TARGET: "12.0"
  SWIFT_VERSION: "5.9"
  IPHONEOS_DEPLOYMENT_TARGET: "15.0"

targets:
  MacAppStoreDiscovery:
    type: application
    platform: macOS
    sources:
      - path: Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.iosstore.macappstorediscovery
      PRODUCT_NAME: MacAppStoreDiscovery
      MACOSX_DEPLOYMENT_TARGET: "12.0"
      SWIFT_VERSION: "5.9"
      INFOPLIST_FILE: Sources/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Mac App Store Discovery
        CFBundleIdentifier: com.iosstore.macappstorediscovery
        CFBundleName: MacAppStoreDiscovery
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "12.0"
        NSHumanReadableCopyright: "Copyright © 2025. All rights reserved."
        NSMainStoryboardFile: Main
        NSPrincipalClass: NSApplication
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSRequiresAquaSystemAppearance: false
    dependencies:
      - sdk: Foundation.framework
      - sdk: AppKit.framework
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - sdk: Security.framework
      - sdk: Network.framework
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        inputFiles:
          - "$(SRCROOT)/Sources"
        outputFiles:
          - "$(DERIVED_FILE_DIR)/swiftlint-output"

  MacAppStoreDiscoveryTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.iosstore.macappstorediscovery.tests
      PRODUCT_NAME: MacAppStoreDiscoveryTests
    dependencies:
      - target: MacAppStoreDiscovery

  MacAppStoreDiscoveryUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: UITests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.iosstore.macappstorediscovery.uitests
      PRODUCT_NAME: MacAppStoreDiscoveryUITests
    dependencies:
      - target: MacAppStoreDiscovery

schemes:
  MacAppStoreDiscovery:
    build:
      targets:
        MacAppStoreDiscovery: all
    test:
      targets:
        - MacAppStoreDiscoveryTests
        - MacAppStoreDiscoveryUITests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 